### ISSUE TITLE
controlnet doesn't work 

### ISSUE THREAD

**Issue by azizzainih** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#224]
Hello,

why controlnet doesn't work at all in Auto-photoshop but work on web-ui?

no error or anything but when i hit generate it generate image without controlnet and the generated image will show up at "view mask" in the controlnet tab instead of controlnet generated canny or depth guide image.

i have check the enabled option, set correct modul, and set CtrlNet image source.

Thanks in advance.

i'm using:

photoshop v24.1
latest version of automatic1111
latest version of controlnet 

arguments: --autolaunch --xformers --api --no-half --disable-nan-check --precision full --medvram

**Comment by AbdullahAlfaraj** [comment]
It could be that there is a mismatch between the name of the controlnet model and the name of the yaml config file.
And the reason why the image shows in the view mask preview is because the control net failed at creating the detect map image, which normally shouldn't happen. 

Can you provide me with this info:
1) the full name of the controlnet model are you using? ex. "control_canny-fp16"

2) Screenshot of the contentnet settings from auto1111:

![image](https://user-images.githubusercontent.com/7842232/231982981-5f0a0412-4575-4b27-98fb-1f891bac19a6.png)

3) Screenshot of your model directory:

![image](https://user-images.githubusercontent.com/7842232/231981776-278945ea-0c5d-41de-bce7-27cb2149509d.png)

**Comment by azizzainih** [comment]
sure:
controlnet model
![image](https://user-images.githubusercontent.com/35615704/231993267-0fe11fe6-5de2-4cfe-a324-79b55c82ba65.png)

settings from auto1111:
![image](https://user-images.githubusercontent.com/35615704/231992779-1a973ff7-6df6-4de7-82dc-f30376e9172f.png)

model directory:
![image](https://user-images.githubusercontent.com/35615704/231992917-45982821-6059-4c12-a07a-1ef1ccac926a.png)
