### ISSUE TITLE
Inpaint and Outpaint doesnt work for me. 

### ISSUE THREAD

**Issue by XTRMsavage** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#231]
First of all I would like to thank you for your hard-work for making this plugin happen. I would appreciate if you can look into these issues I am having and guide me solving them. Thanks

 Here I just created a simple scene.
<img width="1916" alt="1" src="https://user-images.githubusercontent.com/90519573/233241782-772736c9-2e10-425f-bf34-a6f4bbdcf688.png">

Selected inpaint and wrote prompt for a totem pole.
<img width="1913" alt="2" src="https://user-images.githubusercontent.com/90519573/233241859-2fe98425-611b-4faf-90b9-5b80c3deb534.png">

No totem pole, but something happens.
<img width="1916" alt="3" src="https://user-images.githubusercontent.com/90519573/233242015-c6df902a-b1c8-4493-8723-f6255a47856d.png">

I use txt2img and a totem pole appears 
<img width="1909" alt="4" src="https://user-images.githubusercontent.com/90519573/233242163-bd533ee7-e01d-46c0-909d-2be87ac260fd.png">

Now, I try Outpaint
<img width="1910" alt="5" src="https://user-images.githubusercontent.com/90519573/233242366-91a1a6c2-a51a-4853-9885-467a0765d915.png">

Nothing happens :(
<img width="1912" alt="6" src="https://user-images.githubusercontent.com/90519573/233242503-537b11a9-9e8a-4319-b104-2fcf376c21b4.png">

**Comment by indecentwolf** [comment]
I ran to these same issues today, if you're getting same error like mine in your console:
"ValueError: images do not match"

Looking at your screenshot, you're trying to use inpainting in an odd resolution. I suggest checking out [PR](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9628/files) for a possible fix.

**Comment by zombieyang** [comment]
I think is the same as #241

**Comment by AbdullahAlfaraj** [comment]
@XTRMsavage 
There are a few issues that need to be addressed:

1) To get good results while inpainting, make sure to select the inpaint model and choose latent noise instead of fill for this case.
2) The width-to-height ratio of your image is suboptimal. The closer it is to 1x1 and 512x512, the better the results will be.
3) Your image resolution is too high for outpainting at 3012x512. This may cause Auto1111 to crash unless you have a lot of VRAM.
4) The black mask image you are getting is due to “layer 0”. Deleting it should fix the outpainting issue.

Can you explain why you have a white layer called “layer 0”? Can you use the color picker to check if it’s 100% pure white?

**Comment by ZeroCool22** [comment]
> @XTRMsavage There are a few issues that need to be addressed:
> 
>     1. To get good results while inpainting, make sure to select the inpaint model and choose latent noise instead of fill for this case.
> 
>     2. The width-to-height ratio of your image is suboptimal. The closer it is to 1x1 and 512x512, the better the results will be.
> 
>     3. Your image resolution is too high for outpainting at 3012x512. This may cause Auto1111 to crash unless you have a lot of VRAM.
> 
>     4. The black mask image you are getting is due to “layer 0”. Deleting it should fix the outpainting issue.
> 
> 
> Can you explain why you have a white layer called “layer 0”? Can you use the color picker to check if it’s 100% pure white?

Can you tell me what is wrong?:

✅**Latent Noise** give a very bad result:


https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/13344308/0229d1b1-395e-43e2-8679-f053a9f0fdf3

✅Now **Original & Fill**:


https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/13344308/76281a8e-0118-46a9-9d42-955b345e811a

Original doesn't give any result and Fill give a result but very bad....

*I'm doing a selection of **512x512**.
*Using an **Inpaint Model**.

**Comment by AbdullahAlfaraj** [comment]
@ZeroCool22 , I use the options from the smart preset menu because it adjusts the denoising strength too.
 For latent noise, a high denoising strength is necessary to avoid artifacts. The "original" option requires color variation and will not work with solid colors like white.
As a rule of thumb: 
- Use “original” for inpainting to provide variation, such as when inpainting faces.
- Use “latent noise” for inventing new information, making it suitable for outpainting and in some cases, inpainting.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/2b56c4a1-17e5-4803-a04e-561d028796f6)

**Comment by Lalimec** [comment]
> > @XTRMsavage There are a few issues that need to be addressed:
> > ```
> > 1. To get good results while inpainting, make sure to select the inpaint model and choose latent noise instead of fill for this case.
> > 
> > 2. The width-to-height ratio of your image is suboptimal. The closer it is to 1x1 and 512x512, the better the results will be.
> > 
> > 3. Your image resolution is too high for outpainting at 3012x512. This may cause Auto1111 to crash unless you have a lot of VRAM.
> > 
> > 4. The black mask image you are getting is due to “layer 0”. Deleting it should fix the outpainting issue.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you explain why you have a white layer called “layer 0”? Can you use the color picker to check if it’s 100% pure white?
> 
> Can you tell me what is wrong?:
> 
> ✅**Latent Noise** give a very bad result:
> 
>  2023-05-26.23-59-34.mp4 
> ✅Now **Original & Fill**:
> 
>  2023-05-27.00-02-42.mp4 
> Original doesn't give any result and Fill give a result but very bad....
> 
> 👉 I'm doing a selection of **512x512**. 👉 Using an **Inpaint Model**. 👉 PS Version 24.5

I dont know if you figured it out but 0.7 denoising is too low for latent noise fill. 1 is way to go if there is nothing you want to keep under the mask, or while outpainting in this case.
