### ISSUE TITLE
v1.2.3 (or 4?) - --api unrecognized

### ISSUE THREAD

**Issue by AquatikJustice** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#256]
I have followed the instructions in the README for installing this locally, including adding the --api to the COMMANDLINE_ARGS in webui-user.bat, however when SD starts up it doesn't seem to pick up on that. 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/4640482/c9779e13-c6bb-41b9-986d-bf56226dd9f0)

Everything seems to be running smoothly until I get into PS, then I get the "You forgot to add --api" popup and nothing ever loads.

Not sure about the version number, b/c I installed 1.2.3 from the releases section, but in the plugin window it's showing 1.2.4 in the upper right.

**Comment by AbdullahAlfaraj** [comment]
There are multiple issues here:

1) Your Auto1111 is not mounting the API. You can’t use the plugin until you solve this issue. This could be caused by an outdated Auto1111 webui version.
2) Version 1.2.4 is only available to the public through method 3 (the UXP method) or through early access via Patreon, where patrons have access to the .ccx and .zip files of v1.2.4.
