### ISSUE TITLE
I can use this tool with google colab

### ISSUE THREAD

**Issue by wilzamguerrero** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#27]
hi thanks for this tool, my question is i can use and connect this with google colab for generate the image in photoshop?

**Comment by AbdullahAlfaraj** [comment]
hi @wilzamguerrero, you will have to find a colab that expose automatic1111 webui api using nginx. 
Then you will have to modify the variable SD_URL in "start_server.bat" by overriding its value with the url you get from nginx.

**Comment by AbdullahAlfaraj** [comment]
I have tested the plugin with this colab and it does work.
https://colab.research.google.com/drive/1nbcx_WOneRmYv9idBO33pN5CbxXrqZHu#scrollTo=A6OFCYOzNjDX

it will give you a url , use to overwrite the SD_URL in start_server.bat if you are on windows
here is an example of how it should look like
```
set SD_URL=https://f60db0c0b2314c1e.gradio.app
```
the colab was created by 
https://github.com/ddPn08/automatic1111-colab

**Comment by AbdullahAlfaraj** [comment]
@wilzamguerrero you should run the colab without any modification.
don't select any of the settings just run all the cells as they are.
also, I see that you haven't saved the "start_server.bat" so that could be your problem. 
you need to 
* Close the server 
* Edit the start_server.bat then save it.
* Then run the modified "start_server.bat" again.
