### ISSUE TITLE
How does Ultimate SD Upscaler work in this plugin?

### ISSUE THREAD

**Issue by sabashio** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#316]
It doesn't seem to affect the size of my image or document (assuming my selection box covers the entire document).  Does it just use the pixels already in the image to add detail if it is able to?

**Comment by cdmusic2019** [comment]
You can use 'hires.fix' or adjust the width and height values.

**Comment by AbdullahAlfaraj** [comment]
@sabashio, the output images are smart objects, and you can double-click them to see their actual size. I would recommend starting with a canvas of your target image size, such as 3000x3000, instead of 512x512. Here’s another post related to upscaling and image size https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/203.
The Output size will depend on the target size option you've selected.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/152aebac-2b96-452b-8a07-f24794470e8f)

**Comment by Jonseed** [comment]
@AbdullahAlfaraj when I change the output size to another option in the dropdown, it doesn't change the fields underneath. I can only select "Scale from image size" and it shows the one slider. But if I change it to "custom size," it doesn't change to show two sliders for custom height and width.

**Comment by Jonseed** [comment]
It would be nice to be able to type in values too, instead of using the sliders.

**Comment by Jonseed** [comment]
I also noticed that it doesn't seem to "scale from image size" like the extension works in Auto1111. Instead it scales it from the dimensions set with the height/width sliders. It should detect the size of the image selected, and scale it from that resolution.

**Comment by AbdullahAlfaraj** [comment]
@Jonseed 
Just wanted to clarify that the ‘scale from image size’ feature is working as expected. Remember, the image size is determined by the initial values of the width and height sliders when you hit the red ‘generate’ button. 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/692c6bf4-dc77-48b5-ac1a-d4de5606bb8b)

I’m considering adding labels to clearly indicate the base size for upscaling, similar to what we have in the hi-res fix feature.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/9cfd1d3d-4232-40c6-a72d-cf43db289f82)

also, next version will feature custom width and height sliders for the ultimate SD upscaler

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/31ea671d-7949-4df5-960d-a6eeae7e7c9b)

**Comment by Jonseed** [comment]
@AbdullahAlfaraj that's not how Ultimate SD Upscale works in Auto. In Auto, when you select "scale from image size," it will scale it from whatever size image is currently input in img2img. It does _not_ scale from the size indicated by the width and height sliders. It completely ignores those values.

One problem with how it is implemented in the plugin is what if the image I'm upscaling is already bigger than 2048x2048? The sliders max out at that value, so I cannot upscale an image bigger than 2048x2048 using the plugin. But I can in Auto, because it scales it from the actual size of the image in img2img.

It would be nice if the plugin worked similarly as in Auto, and scaled an image from the size of the actual selection, and not from the size indicated by the height/width sliders.

That'll be great to have the custom width and height sliders (and input fields?)! Looking forward to that.

**Comment by AbdullahAlfaraj** [comment]
@Jonseed,
The main issue here is that when the plugin initially extracts an image from the canvas, it does so at the resolution of the selection, and then rescales it to match the dimensions set by the sliders. For example, if the selection is 5000x5000 and the sliders are set to 512x512, the image will be extracted at 5000x5000 and then scaled down to 512x512.

This behavior has been around for a while and was originally intended to ensure that all images (including the initial image, mask, and control net images) were of the same size before being sent to Auto1111. I don’t think this feature is needed anymore, given that Auto1111 and controlnet are quite robust, but I’ll have to check if there are any side effects of disabling it.

But , if you still need a size greater than 2048, you can use the precise selection mode.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/c87ae77c-51cd-4186-b311-6ed37490914c)

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/b6aa55b5-e950-4b81-a55c-cf2d80edfa1d)
