### ISSUE TITLE
ControlNet Reference mode only work with single controlnet unit

### ISSUE THREAD

**Issue by colinhuang1998** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#347]
Once I use multiple units, it warns:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/77152498/b473a075-e7ad-4757-ad36-6da53aeeb3ee)

Meanwhile my controlnet setting:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/77152498/d5603e58-b04f-4c22-b648-0bedea7d0342)

**Comment by maoli173** [comment]
> it's fixed it in [dd255e8](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/commit/dd255e8fd00cc9de940a526e127ad7850df4cb66), but you will need to wait till I release v1.3.1.

thanks! I got the same issue.Thats annoyed.I want to use lineart to get my sketch and ref to get my pics.

**Comment by jimmylgz** [comment]
i find another bug, when i use multi-controlnet, after i have chosen two different images for two different controlnet, the plugin automatically set two input images into the same image. :(

**Comment by AbdullahAlfaraj** [comment]
Hey @jimmylgz, this isn’t a bug but a feature. If you turn it off, the plugin won’t auto-fill the controlnet, and you’ll have to do it yourself. I was thinking about disabling this if a user adds an image manually. But since most folks are used to the old way of using the plugin where they need to manually fill in the controlnet image, they might not even realize this feature exists as it gets disabled if you add an image manually. 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/5349750d-0821-484c-8554-89d59518c461)

**Comment by jimmylgz** [comment]
> Hey @jimmylgz, this isn’t a bug but a feature. If you turn it off, the plugin won’t auto-fill the controlnet, and you’ll have to do it yourself. I was thinking about disabling this if a user adds an image manually. But since most folks are used to the old way of using the plugin where they need to manually fill in the controlnet image, they might not even realize this feature exists as it gets disabled if you add an image manually.
> 
> ![image](https://user-images.githubusercontent.com/7842232/270039911-5349750d-0821-484c-8554-89d59518c461.png)

I found out this last night as well. It took me a while to realize this and did solve my problem. Thank you very much for your quick reply though.Hopefully will help the other folks!
