### ISSUE TITLE
Middle mouse scroll not working on photoshop panels on Mac

### ISSUE THREAD

**Issue by conlanpatrek** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#409]
Thanks for this plugin, i'm excited to start digging in.

Got it working on mac, photoshop 2024. noticed that I can't scroll the plugin panel using the scrollwheel on my mouse. can only scroll by physically clicking the scrollbar and dragging it.

![Screenshot 2023-11-11 at 1 34 55 PM](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7852096/df30057f-ee3f-49eb-8c12-a8db84535657)

**Comment by AbdullahAlfaraj** [comment]
It works for me on windows! not sure about Mac.
Can you scroll down in the native photoshop interface, like in the `Layers` window? 
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/8404d822-c8e1-440d-97e6-174c43a5b1a1)

**Comment by conlanpatrek** [comment]
I can. Scroll wheel works fine in native panels.

**Comment by conlanpatrek** [comment]
hey hey, here's that recreation i promised you https://www.youtube.com/watch?v=zvTeug3-Ia4

i'm also willing to sling a little code if it comes to it. lmk what you're open to.

**Comment by AbdullahAlfaraj** [comment]
Thank you for sharing the video. It seems to be working perfectly on my Windows 10 OS. I’m curious, do you encounter the same issue when scrolling within the `Second-Auto-photoshop-SD` panel?

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/b59f2fb3-ef65-48e0-ab5b-9f14edf21764)

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/4e749c1a-0894-40ec-a6ad-7baa6c0715bf)

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/0f25b156-b3f7-4e5d-9475-85b1eb38ee6f

**Comment by conlanpatrek** [comment]
I do not encounter the issue on `Second-Auto-photoshop-SD`, another hint perhaps?

**Comment by AbdullahAlfaraj** [comment]
I’ve run into the same problem you’re having with the plugin. The middle mouse button stops working on the main panel, unless I’m hovering over the scroll bar, just like in your video. This isn’t just a MacOS thing.

I think this might be because of the CSS styling. Right now, the main panel uses a trick to act like it’s toggling `display: none` in javascript and CSS by using a combination of `position: absolute` and `visibility: hidden`. 

We had to do this because Photoshop’s HTML rendering engine would throw an error if the plugin tried to toggle the visibility of a bunch of HTML elements all at once https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/34, which is basically what happens every time the plugin switches modes.

I’m planning to go back to using the display property in the main menu, since this problem doesn’t happen in React (the plugin now uses React instead of pure HTML, CSS, and JavaScript).

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/c3518e4d-fdf4-432b-85be-d06a4220fd8a

A workaround that did the trick for me was to undock the plugin and then re-dock it in a different spot. It seemed to solve the problem! Can’t really tell you why, but it did! let me know if it works for you.

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/95b76452-8eb2-4a6b-9700-cb89860202a3

**Comment by conlanpatrek** [comment]
ah, so are you saying it's possible some inactive hidden element is hovering in front, stealing the mouse events?

this makes sense to me. have you looked into also adding `pointer-events: none;` (or `z-index: -1;` if that's not supported, though i suspect this is probably chromium) to your hidden elements? in addition to `position` and `visibility` i mean.

**Comment by conlanpatrek** [comment]
i'd be willing to submit a pr if you think there's a chance that we're barking up the right tree. i've never worked on a photoshop plugin and frankly i'm interested to learn how your dev environment is set up in this repo.

**Comment by AbdullahAlfaraj** [comment]
I've given `pointer-events: none;` a shot, but it didn't seem to do the trick. Personally, I don't believe this issue is rooted in CSS styling. It seems more like a bug related to absolute positioning in Photoshop.

Photoshop does have its fair share of quirks. For instance, `z-index` isn't fully supported. It functions well enough, but you can't place an absolutely positioned element on top of a text field or textarea. Event handlers like `blur` and `focus` can be hit-or-miss, and 'mouseenter' or hover events often get triggered for the wrong element. It's all part of the Photoshop experience! 😅

Here's something you could do. Try reversing the visibility hack and use `display: none;` instead. Also, consider disabling `position: absolute;`. If everything works smoothly without any issues, go ahead and submit a PR. The classes you'll want to modify are `.sp-tab-page` and `.sp-tab-page.visible-hack`

**Comment by conlanpatrek** [comment]
i see! it must be some other webview then. might even explain the discrepancies between OS's. i'll take a look at this asap. thanks for pointing me in a direction bud! excited to get into the code.
