### ISSUE TITLE
img2img doesn't use the same dimensions as original selection, and ControlNet Tile shadowing & stretching

### ISSUE THREAD

**Issue by Jonseed** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#430]
If I have an image of 904 x 1149, and I use precise selection mode to select the entire canvas and do img2img, I get a smart object of size 896 x 1088. If I have an image of 904 x 904, I get a smart object of 896 x 896. Do you know why the dimensions are smaller than the original selection?

This also seems to be related to strange effects when using img2img with ControlNet Tile, where you get a shadowing effect between the img2img image and the ControlNet image, especially if the original image is non-square. If you have a portrait image, the ControlNet image seems to be stretched vertically, and doesn't match the img2img contents.

**Comment by AbdullahAlfaraj** [comment]
Automatic1111 has seen several changes. Initially, it rounded image dimensions to the nearest multiple of 64. Then in a later update, if dimensions weren’t multiples of 64, it would throw an error. To address this, I adjusted the values taken from the width and height slider in the plugin before generating an image. Recently, Automatic1111 seems to have shifted to using increments of 8, which might be causing the size discrepancy you’re noticing. I will have to change increments on our side to 8 instead of 64, (in the next update).

Regarding the ControlNet Tile issue, it’s a bit hard to diagnose without an example. Could you provide one? This would help me better understand the shadowing effect you’re seeing.

**Comment by Jonseed** [comment]
Good to know about the increments. Does Automatic1111 also use those increments when doing img2img, and then just resizes the image in the end to match the original image size?

@AbdullahAlfaraj Below is an example of the ControlNet Tile issue. I added the white inset border on the original image to more easily see the shadowing and stretching problem. Using the same img2img input image and ControlNet Tile input image (auto image), tile resampling and control_v11f1e_sd15_tile model and mode to "ControlNet is more important", with a non-square image (portrait), the image is stretched vertically, causing a shadowing effect at lower denoising, and just being stretched at higher denoising. This doesn't happen in Automatic1111 with the same settings (see the lower image). I don't know if it is related to the increments issue, but for some reason the two input images are not aligned. 

The original image on the left is 768 x 1082. Doing img2img on it, with ControlNet Tile, and denoising at 0.6, and you get the center image. You can see there is some shadowing happening at the top and bottom edges with the white inset border, because the image is being stretched vertically. If you increase the denoising to 0.9, you get the image on the right, where you can readily see the image has been stretched about 70 pixels vertically. It seems the ControlNet input image is likely the culprit, since higher denoising would use less of the img2img image, and rely more on the ControlNet image, so it seems the ControlNet image is stretched vertically for some reason and doesn't match the img2img input image. Strangely, the center image smart object is 768 x 1216 pixels (134 pixels taller), and the right image smart object is 768 x 1024 pixels (58 pixels shorter), neither of which matches the original image size of 768 x 1082 (which is perhaps related to the increments issue, since 1082 isn't divisible by 64?).

![shadowing](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/40897189/c48d0bb5-89d5-4a99-872d-3a59febf21e6)

If I do the exact same operation with same settings in Automatic1111, I get the correct result, without shadowing or stretching, as below.

![no-shadowing-stretching-auto1111](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/40897189/bd485315-520a-4558-a979-79cf5ae331a6)

**Comment by AbdullahAlfaraj** [comment]
Thank you for the detailed explanation; it’s quite helpful.

>Does Automatic1111 also use those increments when doing img2img, and then just resizes the image in the end to match the original image size?

I believe Automatic1111 will always output images that are divisible by 8. The exception to this is when you do inpaint in full resolution. The result of the inpaint operation gets composed into the original image, which could be of any size.

The stretching issue you mentioned is likely caused by the large 64-pixel increment. In version 1.4.1, the increment is set to 8px, whereas in v14.0, it was set to 64px.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/47f69798-8b26-47bb-b2e0-896c91bb4a92)

In this clip, I showcase the inpainting result (with inpaint in full resolution disabled). The one on the left is in 1.4.0, the one on the right is done in v1.4.1 with an increment of 8px, the new version is more aligned with original/input image.

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/17ea616c-ce55-4536-863e-d3e39bada830


>Strangely, the center image smart object is 768 x 1216 pixels (134 pixels taller),

Regarding the anomaly where the center image smart object is 768 x 1216 pixels (134 pixels taller), I couldn’t replicate this. It’s probably an anomaly where you might have modified the height slider by mistake.

**Comment by Jonseed** [comment]
That's great. I tried 1.4.1 and it seems to work much better now. Thank you!
