### ISSUE TITLE
README is not actual due to last interface of plugin

### ISSUE THREAD

**Issue by inomax5** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#79]
There is no buttons "Init inpaint Mask" etc. Please give us instructions how to work with last interface of plugin by updating README. Thanks a lot in advance!

**Comment by AbdullahAlfaraj** [comment]
@inomax5 we do need to people to volunteer and helps with documentations.
if you or anyone would like to help, please contact me here or on our development discord.

**Comment by FugueSegue** [comment]
This is a serious problem. I have successfully installed the plugin today. But I don't know how it works. I want to inpaint. I don't know how. The tutorial video was made two months ago. The interface is completely different. There is no "Init Inpaint Mask".

Please make a new tutorial video. It is astonishing that this issue was posted a month ago and there is no new tutorial video. Also, do not use background music. Music is not important. It makes it difficult to understand what you are saying.

Please forgive my criticism. This looks like a very good plugin. I want to use it. But I cannot use it unless there is some sort of documentation or instructions.

**Comment by AbdullahAlfaraj** [comment]
This has been resolved a while back, we've added a wiki section plus new tutorials that showcase how to use the new interface.
